version: '3.7'

services:
  huawei:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: huawei
    command: npm run admin
    volumes:
      - /data/nginx/acme.sh-lingdou:/ssl/lingdou
