version: '3.7'

services:
  huawei:
    build:
      context: .
      dockerfile: ./Dockerfile
    env_file: .env
    volumes:
      - /data/nginx/acme.sh-lingdou:/ssl/lingdou
      - /data/nginx/acme.sh-sureemed:/ssl/sureemed
