auth:
  identity:
    methods:
      - 'password'
    password:
      user:
  scope:
    project:
      name: 'cn-east-3'

host:
  token: 'https://iam.cn-east-3.myhuaweicloud.com'
  elb: 'https://elb.cn-east-3.myhuaweicloud.com'
  docker: 'https://swr-api.cn-east-3.myhuaweicloud.com'
  qiniu:
    sslcert: 'https://api.qiniu.com'
